name: .NET 8 Continuous Integration with GitHub, GitHub Actions and Nuget Packages

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Move to folder
      run: cd ./Tapioca.HATEOAS/
      
    - name: Generate Release
      run: dotnet build -c release
      
    - name: Generate Package
      run: dotnet pack -c release -o ./dist/Tapioca.HATEOAS.1.0.7.${{github.run_id}}.nupkg
      
    - name: Publish Package
      run: dotnet nuget push "./dist/Tapioca.HATEOAS.1.0.7.${{github.run_id}}.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s "https://api.nuget.org/v3/index.json"

